// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvzgszkliqkzfaulpvju.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2emdzemtsaXFremZhdWxwdmp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMjkwMDMsImV4cCI6MjA3MTcwNTAwM30.cz09qE_Pem9ViV44Q9W75nNWIUOzx8o3n0_yYL9j9FY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});