// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uaeijkjsokrmikfduczq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhZWlqa2pzb2tybWlrZmR1Y3pxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMjY4ODMsImV4cCI6MjA3MTcwMjg4M30.VPUpzCAUftqWPnGTeh5wsMfak0NqZOtJJSuaIw3wlC4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});